### ISSUE TITLE
Masked unaffected by gun (Modded Suits)

### ISSUE THREAD

**Issue by TGG12464** [MehimoNemo/LethalCompanyShrinkRay#100]
He just starts flying or goes into the ground. 
This is with replaced suits and models. I wouldn't be surprised if not fixable but was confused when first used gun on masked that was a boykisser as they just ducked into the ground like some mole. (Specificly LethalBoykisser from TheBruhFr2)
Reporting just incase a fix is possible because it does work on friend with the model replaced just not their masked version.

**Comment by AboveFire** [comment]
Oh, yeah I didn't think about that when working with the masked modelled. It's most likely fixable, but it'll require some code to adapt.

**Comment by TGG12464** [comment]
> Oh, yeah I didn't think about that when working with the masked modelled. It's most likely fixable, but it'll require some code to adapt.

Okay! Hope to see a fix in the future. Also where may a changelog be for updates?

**Comment by AboveFire** [comment]
The changelog is in the section changelog on thunderstore. Or we also post it on discord. It's also in the folder "thunderstore" in the GitHub.
