### ISSUE TITLE
Add size resetting at end of level, add it as an option in the config, add player size resetting on death(if it doesn't naturally occur)

### ISSUE THREAD

**Issue by MehimoNemo** [MehimoNemo/LethalCompanyShrinkRay#14]

**Comment by MehimoNemo** [comment]
Added size resetting, but didn't do config set up yet, should be pretty easy to do

**Comment by NiroDev** [comment]
Pay attention to GrabbablePlayerList if doing so. Can't be cleared anymore then!

**Comment by NiroDev** [comment]
Size resetting felt a bit weird and got removed in 0.2.0. we could consider making it an option in later development
