### ISSUE TITLE
Fix shrunk players hands being at armpit height permanently

### ISSUE THREAD

**Issue by MehimoNemo** [MehimoNemo/LethalCompanyShrinkRay#16]

**Comment by NiroDev** [comment]
Can be fixed by changing "spine" instead of the global transform. But that one shrinks the player in the center, making them float. Changing localPosition can cause conflicts. Still searching for solutions..

**Comment by AboveFire** [comment]
Fixed, solution was to rebuild the rig after size change and make sure to write default values for the rig before rebuilding it cause it gets wonky if not.
