### ISSUE TITLE
Fix item offset code to be less janky

### ISSUE THREAD

**Issue by MehimoNemo** [MehimoNemo/LethalCompanyShrinkRay#19]
Currently, every time you pick up an item while small, if it's in the list of screen blocking items, it tries to offset it to a specific location. This doesn't put the item at the same coordinates every time... Either find a better way of doing it dynamically, or create a list of offsets. I vote we do it dynamically for better integration with other mods.

**Comment by NiroDev** [comment]
fixed recently with automatic item scaling for playerHeldBy's pov
