### ISSUE TITLE
Shrink ray teleports to weird coordinates from players inventory at end of round sometimes

### ISSUE THREAD

**Issue by MehimoNemo** [MehimoNemo/LethalCompanyShrinkRay#45]
Shrink ray turns invisible in players inventory at end of round, dropping makes it vanish

**Comment by MehimoNemo** [comment]
Nevermind, found it
![image](https://github.com/MehimoNemo/LethalCompanyShrinkRay/assets/22804739/e2d58202-57d4-4af2-bf52-404c6ab26fa1)

**Comment by NiroDev** [comment]
Likely fixed. Not happening anymore
