### ISSUE TITLE
Certain players are not able to shrink or be shrunk sometimes??

### ISSUE THREAD

**Issue by MehimoNemo** [MehimoNemo/LethalCompanyShrinkRay#46]
I have no idea, happens in multiplayer after playing for a while

**Comment by NiroDev** [comment]
happens mainly when trying to shrink a player while being shrunk. aiming at the feet works, while head doesn't sometimes. likely a position problem of the ray that's casted to check for collisions

**Comment by NiroDev** [comment]
Fixed with new SphereCast.. may come up again with linecast in another way
