### ISSUE TITLE
HELD OBJECT IS NULL spamming in console causing crash

### ISSUE THREAD

**Issue by MehimoNemo** [MehimoNemo/LethalCompanyShrinkRay#50]
![image](https://github.com/MehimoNemo/LethalCompanyShrinkRay/assets/22804739/68e85b5e-695f-4597-824b-19e934334196)
Happens sometimes??? not sure why...

**Comment by NiroDev** [comment]
a relict of the old way we handled friendlyFlight. fixed with #39
