### ISSUE TITLE
Jump to ungrab randomly appearing on full size players screens

### ISSUE THREAD

**Issue by MehimoNemo** [MehimoNemo/LethalCompanyShrinkRay#51]
Occurred during extended multiplayer testing

**Comment by NiroDev** [comment]
Attempted to fix this: https://github.com/MehimoNemo/LethalCompanyShrinkRay/commit/7d531f377d0c7ad919f726f67f46d2747ebee2b1
Requires further testing

**Comment by NiroDev** [comment]
Fixed. Reason was a compare with the playersize, which could vary after shrinking/enlarging by 0.00001. Works after Mathf.Round
