### ISSUE TITLE
Suggestion: Using the shrink ray on enemies

### ISSUE THREAD

**Issue by budr2quid** [MehimoNemo/LethalCompanyShrinkRay#63]
I think the shrink ray should work on most enemies too, making dealing with them easier(dogs, thumper, giant, etc) or harder like for coilhead(pretty sure the size doesn't affect how it could kill you, making it smaller just makes it harder to spot)

**Comment by NiroDev** [comment]
It's a planned feature for the future, which we work towards. The code already detects if an enemy is hit and if which type it is, but we're currently working towards a 1.0 release, so the priorities are mainly on stability and reliability of features that "should" already work.

Once that's done, we'll work on shrinking items and enemies. Feel free to suggest any ideas you have here, or preferably in our discord forum post that's linked in the readme

**Comment by NiroDev** [comment]
Will be part of the full release in a few days.
