### ISSUE TITLE
How to organize these files into an IDE recognizable project?

### ISSUE THREAD

**Issue by BoredBean** [MehimoNemo/LethalCompanyShrinkRay#70]
I tried Visual Studio for the "LethalCompanyTemplate.sln", but it didn't work.
Next, I tried the ".csproj" in "netOutputLCShrink", didn't work either.
Then I noticed a ".idea" folder committed for some reason so I also tried IDEA. Still didn't work.

I'm not familiar with .NET development.
I can see all the codes are committed in "LethalCompanyTemplate" but have no idea about how to organize them into a compileable project.
Or which IDE should I use?

**Comment by NiroDev** [comment]
Hey, the GitHub repository is missing a .csproj file inside the LethalCompanyTemplate folder for the .sln to work.

We're using visual studio to build it. You can reach out to me on discord (niro1996) and I'll hand you the csproj file.

May I can ask why you would like to build it locally?

**Comment by BoredBean** [comment]
As I mentioned on Discord earlier, I am studying your work to learn how to use third-party RPC functions to synchronize audio playback in-game.
I think I'm making some progress.

**Comment by NiroDev** [comment]
Will close this issue. Let me know on discord when you need it :)
