### ISSUE TITLE
Grabbed during gameover breaks the game

### ISSUE THREAD

**Issue by AboveFire** [MehimoNemo/LethalCompanyShrinkRay#77]
We got fired (game over) while I was in someone's hand and when everything broke.
When the game restarted, I was stuck in the person's hand, I was small, and we kept all the stuff we had in the last game?!? I logged off and logged back in and I was still small. We had to restart the lobby.

So make sure the game over is handled correctly for grabbed people. Either by staying grabbed and working or by ungrabbing.

**Comment by NiroDev** [comment]
Fixed in the next release.
