### ISSUE TITLE
[Old Issue] hit shrunken player twice by shovel can make player be flaten and after a short time, player will get very mini size, the thing is mini player cannot able to move and stay in the air after escaping grab

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#80]
@NiroDev  same as topic, 4 am at this moment for me, just for this issue

**Comment by CoolLKKPS** [comment]
uh btw i didn't test the new version, a bit lazy now...

**Comment by CoolLKKPS** [comment]
still exist

**Comment by CoolLKKPS** [comment]
this bc littlecompany set a hard limit call `DeathShrinking`, player size normally cannot below 0.2f, but mini player size are below 0.2f, that's the reason why mini player have many issues

**Comment by CoolLKKPS** [comment]
u also set the hard limit in `DefaultPlayerSize`

**Comment by CoolLKKPS** [comment]
u also set the hard limit in `DefaultPlayerSize`, u need to change the hard limit to 0.07f, that's the mini player size value

**Comment by CoolLKKPS** [comment]
the best size change step value is `0.31`

**Comment by NiroDev** [comment]
Anything below 0.2 is bugged. My first goal here will be to avoid any shrinking/enlarging during the goomba animation (e.g. from shovel), including another goomba on top of it

**Comment by CoolLKKPS** [comment]
tbh, bc mini size are still exist, even i like it, but now its a problem, but yea 0.07f mini player are so tiny, i like it

**Comment by NiroDev** [comment]
With anything below 0.2 you can currently:
- Get stuck behind ladders
- Always get stuck when exiting ladders
- Sometimes clip through walls and ground

Once we found the time to fix these major issues, we will enable going below the current limitation... because i like it too :)

**Comment by NiroDev** [comment]
Fixed in 1.0.5
