### ISSUE TITLE
Add a way to scale players back to normal size

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#81]
if player is not `DefaultPlayerSize` and `enlarging/shrinking` and change size will over/below than `DefaultPlayerSize` in one step, then the player should return to `DefaultPlayerSize`

**Comment by NiroDev** [comment]
Not sure if I got this right. So for example you have PlayerSizeStep set to 1 and Deathshrinking disabled, then you would shrink too the minimum, which is 0.2 and with enlarge you would go to 1.2. Is that what you mean?

**Comment by CoolLKKPS** [comment]
@NiroDev no

**Comment by CoolLKKPS** [comment]
if player size are `0.99` and enlarge step are `0.02`, `0.99+0.02` is `1.01` but that's not the normal size value, what i mean is, if player size are below the normal size but enlarge can over than normal size in one step, should bring player size go back to normal size

**Comment by CoolLKKPS** [comment]
same as shrink

**Comment by NiroDev** [comment]
Shrink shouldn't stop at normal size too. E.g. if player size is <kbd>1.4</kbd> and <kbd>PlayerSizeChangeStep=1.0</kbd>, then the player should shrink to <kbd>0.4</kbd> instead of <kbd>1.0</kbd>. Same if player size is <kbd>0.4</kbd> and the player gets enlarged. Then it should be <kbd>1.4</kbd> and not <kbd>1.0</kbd>, too.

**Comment by CoolLKKPS** [comment]
ok will change the title to let u know why i really recommend this

**Comment by NiroDev** [comment]
I've got another idea: Implement a mode-selection user interface for the shrink ray. Internally there are currently 3 modes
- Shrinking
- Enlarging
- Normalizing (e.g. used for when players die)

A mode selection showed on screen, where you can swap between these 3 would allow people to go back to normal size (whatever is set in <kbd>DefaultPlayerSize</kbd>) and also get rid of the Middle-Mouse-Button usage for enlarging. I would use InputUtils for binding then two new mode-selection keys then.

**Comment by CoolLKKPS** [comment]
uh `Normalize` mode? yes a good solution, but vr player won't able to use that keybinds

**Comment by CoolLKKPS** [comment]
but yea, good idea!

**Comment by CoolLKKPS** [comment]
for a party group, i don't really want people to grab each other, that not only cause many bug, but also some people don't like that
@NiroDev u also need to think about `potion` item btw

**Comment by CoolLKKPS** [comment]
and oh... i think there's another old issue

**Comment by NiroDev** [comment]
> u also need to think about `potion` item btw

Got a suggestion from someone to make potions time-based and loose the effect after a configured time. That could go hand in hand with this.

**Comment by CoolLKKPS** [comment]
uh well i don't like that tbh, but you can create a new potion type to avoid conflict

**Comment by CoolLKKPS** [comment]
@NiroDev not mean time-based potions is bad, but just not replace original one pls

**Comment by NiroDev** [comment]
nono, i won't replace the default behaviour. it would be an additional, optional config

**Comment by NiroDev** [comment]
Moved to [Content-ideas](https://github.com/MehimoNemo/LethalCompanyShrinkRay/wiki/Content-ideas) wiki page.
