### ISSUE TITLE
[Error  : Unity Log] OverflowException: Writing past the end of the buffer

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#83]
[Error  : Unity Log] OverflowException: Writing past the end of the buffer
Stack trace:
Unity.Netcode.NamedMessage.Serialize (Unity.Netcode.FastBufferWriter writer, System.Int32 targetVersion) (at <895801699cfc4b4ab52267f31e2a4998>:IL_002E)
Unity.Netcode.NetworkMessageManager.SendMessage[TMessageType,TClientIdListType] (TMessageType& message, Unity.Netcode.NetworkDelivery delivery, TClientIdListType& clientIds) (at <895801699cfc4b4ab52267f31e2a4998>:IL_00D8)
Unity.Netcode.NetworkMessageManager.SendMessage[T] (T& message, Unity.Netcode.NetworkDelivery delivery, System.UInt64 clientId) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0012)
Unity.Netcode.NetworkConnectionManager.SendMessage[T] (T& message, Unity.Netcode.NetworkDelivery delivery, System.UInt64 clientId) (at <895801699cfc4b4ab52267f31e2a4998>:IL_002D)
Unity.Netcode.CustomMessagingManager.SendNamedMessage (System.String messageName, System.UInt64 clientId, Unity.Netcode.FastBufferWriter messageStream, Unity.Netcode.NetworkDelivery networkDelivery) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0082)
LittleCompany.Config.ModConfig+SyncHandshake.HostConfigRequested (System.UInt64 clientId, Unity.Netcode.FastBufferReader reader) (at <a48d6a89b6574c0596ecfebe25f7b496>:IL_005F)
Unity.Netcode.CustomMessagingManager.InvokeNamedMessage (System.UInt64 hash, System.UInt64 sender, Unity.Netcode.FastBufferReader reader, System.Int32 serializedHeaderSize) (at <895801699cfc4b4ab52267f31e2a4998>:IL_00CB)
Unity.Netcode.NamedMessage.Handle (Unity.Netcode.NetworkContext& context) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0022)
Unity.Netcode.NetworkMessageManager.ReceiveMessage[T] (Unity.Netcode.FastBufferReader reader, Unity.Netcode.NetworkContext& context, Unity.Netcode.NetworkMessageManager manager) (at <895801699cfc4b4ab52267f31e2a4998>:IL_00B2)
Unity.Netcode.NetworkMessageManager.HandleMessage (Unity.Netcode.NetworkMessageHeader& header, Unity.Netcode.FastBufferReader reader, System.UInt64 senderId, System.Single timestamp, System.Int32 serializedHeaderSize) (at <895801699cfc4b4ab52267f31e2a4998>:IL_00FF)
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.NetworkMessageManager:HandleMessage(NetworkMessageHeader&, FastBufferReader, UInt64, Single, Int32)
Unity.Netcode.NetworkMessageManager:ProcessIncomingMessageQueue()
Unity.Netcode.NetworkManager:NetworkUpdate(NetworkUpdateStage)
Unity.Netcode.NetworkUpdateLoop:RunNetworkUpdateStage(NetworkUpdateStage)
Unity.Netcode.<>c:<CreateLoopSystem>b__0_0()

**Comment by CoolLKKPS** [comment]
when people joining

**Comment by NiroDev** [comment]
Attempt to fix this in 1.0.5, which will be uploaded during the day

**Comment by NiroDev** [comment]
Should be fixed. If this occures again feel free to re-open the issue.
