### ISSUE TITLE
[Suggestion] change jetpack size will affect jetpack performance, to make shrunken player easy control the jetpack

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#84]
same as topic

**Comment by NiroDev** [comment]
Good suggestion! I will check later how hard that would be to adjust

**Comment by CoolLKKPS** [comment]
well too many tiny `flying man` crash when landing, so for now, best not using jetpack if too tiny

**Comment by NiroDev** [comment]
Moved to [Content-ideas](https://github.com/MehimoNemo/LethalCompanyShrinkRay/wiki/Content-ideas) wiki page.
