### ISSUE TITLE
[Suggestion?] disable furniture related keybinds for player that size are below a specify value, to make some feature from the config work

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#85]
same as topic

**Comment by NiroDev** [comment]
Assume you mean "[Shrunken]CantOpenStorageCloset". Would only make sense that small players can't move anything, if they're too weak to even open the door. Good suggestion!
May rename that config option to something more general like "[Shrunken]CantMoveShipFurniture"?

**Comment by NiroDev** [comment]
Moved to [Content-ideas](https://github.com/MehimoNemo/LethalCompanyShrinkRay/wiki/Content-ideas) wiki page.
