### ISSUE TITLE
[Old Issue] no player grab cooldown

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#86]
suggestion: if player exit the grab (no matter escape grab or drop by player), will trigger a cooldown and mark the player who exit the grab a `ungrabble` status, for both player/monster the cooldown always 0.5s (reduce development works); but in the mean time, the player only can escape after held by other player for 0.5s

**Comment by CoolLKKPS** [comment]
i got a report from my party member that say this issue still exist, so

**Comment by NiroDev** [comment]
Fixed with 1.0.7
