### ISSUE TITLE
[1.0.7] Turrets shoot upwards when targeting a scaled player

### ISSUE THREAD

**Issue by HerezStarzo** [MehimoNemo/LethalCompanyShrinkRay#87]
Both in single player and multiplayer modes, turrets have the ability to somehow shoot through solid surfaces including walls and closed doors enabling for unfair deaths to which the player should of been safe behind cover. 

I also want to report issues with turrets activating on their own on the map whenever another player in a multiplayer setting _(or a single player setting)_ consumes either a heavy or light potion, almost as if they know exactly where that player is on the map.

_(This may also apply to some of the enemies pathfinding AI as well but that is uncertain which is entirely based on the assumption that they look down at the ground and up at the ceiling either repeating the same pathfinding patterns or standing still completely.)_

Hope this info was enough to convey the issue as this mod is hella fun.

Thanks.

**Comment by NiroDev** [comment]
I'll look into this in the evening. Likely an oversight from the recent change to make turrets able to target smaller players. 

Sorry for the inconvenience and thank you for reporting the issue this detailed

**Comment by HerezStarzo** [comment]
As of right now the issue seems to be fixed. Turrets are not longer activating and deactivating and can no longer kill players behind walls and doors based on testing. I will notify you in this thread to mention anything else that may come up, maybe in a heavily multiplayer environment. Thanks!

**Comment by HerezStarzo** [comment]
Not sure if this is an issue with tiny company, but now when turrets detect you in a line of sight, they aim directly upwards. and shoot upwards.

**Comment by NiroDev** [comment]
I had to adjust their aiming and lowered it from our side. 
Not sure if tiny company patches this aswell. I'll ask the mod dev.
You can use the new config option "DefaultPlayerSize" as an alternative way to change your default scale. 

I've tested the turret aiming for sizes between 0.2 and 1.7 and it worked decently so far. Only shoots too high if you stand very close to it. 
Once I have more time again I'll revisit this and see if I can adjust it better than now

**Comment by NiroDev** [comment]
Aiming is decent as of now. Might get a rework later on
