### ISSUE TITLE
[Discussion] Ways to nerf the ShrinkRay

### ISSUE THREAD

**Issue by NiroDev** [MehimoNemo/LethalCompanyShrinkRay#89]
Opened this thread as a way to collect ideas on how to nerf the ShrinkRay, as it's too powerful right now.

My first suggestion would be to make the usage cost a good amount of battery. A tiny amount, if no target was hit. Maybe even make the amount of battery it costs relative to the size difference or target type (enemy, item, player).

**Comment by catlabeler** [comment]
shrink ray could overheat if used too much per moon, and cool off when changing moons (max usage basically)

**Comment by NiroDev** [comment]
Battery usage and overheating will come in 1.1.0, which is to be expected very soon
