### ISSUE TITLE
Flashlights not saving between sessions

### ISSUE THREAD

**Issue by LonePolar** [MehimoNemo/LethalCompanyShrinkRay#94]
There seems to be a bug where when this mod is active, any flashlights (both regular and pro) that are either being held by employees or placed in the storage cupboard will be lost once you save and reload the game. I can confirm shovels and jetpacks stay, and haven't yet had time to try all items. I recently created a modpack and had this issue, so was disabling mods one at a time (whilst using LethalDevMode to spawn flashlights back in to the ship) until the flashlights stopped disappearing, which was when LittleCompany was disabled. Upon re-enabling the mod the flashlights that stayed when it was disabled were present upon the first load of the save file, but once I saved and reloaded, all flashlights had disappeared from the ship again. It could be a conflict with another mod, and I will be investigating further in case it is when I'm able to, but I wanted to bring this to attention in case it is specifically this mod causing the issue, as otherwise it has been a really cool mod to use so far.

**Comment by NiroDev** [comment]
I did a couple fixes for item saving in 1.2.0 and will test it again in the evening. Have you used a version >= 1.1.0?

**Comment by NiroDev** [comment]
Could also be a conflict with other mods such as BetterItemSaving, as I haven't had the time to test it with other mods yet

**Comment by NiroDev** [comment]
Tested it with v1.2.0 and it seems to work as intended again. Can you verify that please?
Thanks for reporting the issue and thank you for your kind words. Glad you enjoy the mod :)

**Comment by LonePolar** [comment]
I will be able to test tomorrow as I do not have access to my PC. Looking at dates and when I was last on Lethal Company I would have most likely been on 1.1.2. when disabling the mod. I'll get back to you as soon as I can on this

**Comment by LonePolar** [comment]
Just tested and using both LethalDevMode to spawn and save flashlights as well as purchasing via the store and ship drop (with completing a day) I can verify that flashlights are being correctly saved between sessions now, this is with the latest version installed (1.2.1) and all other mods active.
