### ISSUE TITLE
[Issue] u can fall though the ground after interact with scaled terminal while shrunken

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#95]
tbh scale ship unlockable feature still need more test

**Comment by NiroDev** [comment]
I will take a look at this issue today

**Comment by NiroDev** [comment]
Wasn't able to reproduce this, but will set the y coordinate to the same position (relative to the terminal position on entering) when leaving the terminal. 
That should fix this issue in the next version

**Comment by NiroDev** [comment]
Does it still happen?

**Comment by CoolLKKPS** [comment]
uh sorry i didnt test that part, a bit busy, but as far as i know u might need to worry about the minimum size of the things within the cruiser when shrinking the cruiser
