### ISSUE TITLE
[Potential issue] issue when killing player

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#96]
@NiroDev i haven't test this part, but many mods that can kill player are all malfunction now and throw exception, in v55, so i sug u to check ur mod

**Comment by NiroDev** [comment]
We noticed that there are a couple changes to this method, but haven't had the time yet to check which. Will be on my list of things to take a closer look at. We "should" be mostly fine though as we're only running our custom code in patches for this method.

**Comment by NiroDev** [comment]
https://github.com/MehimoNemo/LethalCompanyShrinkRay/blob/main/LittleCompany/components/GrabbablePlayerList.cs line 44

We're fine, because we commented out the other parameter. If we wouldn't, then it would throw an exception as the order is wrong, as a new parameter got added in the middle.
